# logging.file.name=logs/app.log
# logging.pattern.file=%d %p %c{1.} {%t} %m%n
# logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
# h2:
#  console:
#    enable: true
#properties:
# hibernate:
#  dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://sql5.freesqldatabase.com/${DB_NAME}

    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql



hacker:
  post:
    pageSize: 10
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error


